import Head from "next/head";
import React from "react";
import Navbar from "./navbar";

const Layout = ({ children }: { children: React.ReactElement }) => {
  return (
    <>
      <Head>
        <title>T3 Stack Demo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="mx-auto px-2 lg:container">{children}</main>
    </>
  );
};

export default Layout;
